### ISSUE TITLE
Implement outstanding functions for Lenovo

### ISSUE THREAD

**Issue by kolsa** [metal-stack/go-hal#11]
...that are:
- ConfigureBIOS
- EnsureBootOrder
- IdentifyLEDState
- IdentifyLEDOn
- IdentifyLEDOff
- Console

**Comment by GeertJohan** [comment]
This issue is still referenced from https://github.com/metal-stack/go-hal/blob/81ae947778025a56f4dd9d54d38f1a09de31e0ef/internal/vendors/gigabyte/gigabyte.go#L158
